-- ============================================================
-- Circle Health — Supabase schema (PostgreSQL)
-- Generated from JPA entities (Hibernate DDL export).
-- Run in Supabase SQL Editor on a fresh project.
-- 32 tables. app_users is the app's OWN user table (not auth.users);
-- the backend does its own JWT auth via password_hash.
-- ============================================================

    create table app_users (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        name varchar(100) not null,
        email varchar(180) not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create table body_measurement (
        arms_cm float(53),
        body_fat_percentage float(53),
        chest_cm float(53),
        hips_cm float(53),
        measured_on date not null,
        thighs_cm float(53),
        waist_cm float(53),
        weight_kg float(53),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        notes varchar(1000),
        primary key (id)
    );

    create table exercise (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        instructions varchar(3000),
        difficulty varchar(255),
        equipment varchar(255),
        media_url varchar(255),
        muscle_group varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table favourite_exercise (
        created_at timestamp(6) with time zone not null,
        exercise_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        primary key (id),
        unique (user_id, exercise_id)
    );

    create table food (
        calories float(53),
        carbohydrates float(53),
        custom_food boolean not null,
        fat float(53),
        fibre float(53),
        nutrition_basis_quantity float(53),
        package_quantity float(53),
        protein float(53),
        saturated_fat float(53),
        serving_size float(53),
        sugar float(53),
        suggested_serving_quantity float(53),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        owner_id bigint,
        updated_at timestamp(6) with time zone,
        allergen_tags varchar(2000),
        dietary_tags varchar(2000),
        ingredients_text varchar(5000),
        barcode varchar(255) unique,
        brand varchar(255),
        measurement_type varchar(255),
        name varchar(255) not null,
        nutrition_basis_unit varchar(255),
        package_unit varchar(255),
        serving_unit varchar(255),
        suggested_serving_unit varchar(255),
        primary key (id)
    );

    create table generated_meal_plan (
        calorie_target integer,
        saved boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        grocery_list_json text,
        name varchar(255) not null,
        plan_json text,
        primary key (id)
    );

    create table generated_workout_plan (
        days_per_week integer,
        saved boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        goal varchar(255),
        name varchar(255) not null,
        plan_json text,
        primary key (id)
    );

    create table goals (
        completed_date date,
        start_date date not null,
        start_value float(53),
        target_date date,
        target_value float(53) not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        direction varchar(20) not null check (direction in ('DECREASE','INCREASE','MAINTAIN','AT_LEAST','AT_MOST')),
        status varchar(20) not null check (status in ('ACTIVE','COMPLETED','PAUSED','FAILED','ARCHIVED')),
        unit varchar(20) not null,
        type varchar(40) not null check (type in ('WEIGHT','BODY_FAT','WAIST','PROTEIN','CALORIES','WATER','SLEEP','WORKOUT_FREQUENCY','STREAK')),
        title varchar(140) not null,
        primary key (id)
    );

    create table grocery_lists (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        meal_plan_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table grocery_item (
        checked boolean not null,
        quantity float(53),
        created_at timestamp(6) with time zone not null,
        grocery_list_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        category varchar(255),
        name varchar(255) not null,
        unit varchar(255),
        primary key (id)
    );

    create table meal (
        quality_score integer,
        reusable boolean not null,
        created_at timestamp(6) with time zone not null,
        eaten_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        meal_type varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table meal_food (
        quantity float(53),
        created_at timestamp(6) with time zone not null,
        food_id bigint not null,
        id bigint generated by default as identity,
        meal_id bigint not null,
        updated_at timestamp(6) with time zone,
        unit varchar(255),
        primary key (id)
    );

    create table notification (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        read_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        message varchar(1000) not null,
        title varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table profile_cultural_preferences (
        profile_id bigint not null,
        preference varchar(255)
    );

    create table profile_custom_allergies (
        profile_id bigint not null,
        allergy varchar(255)
    );

    create table profile_custom_cultural_preferences (
        profile_id bigint not null,
        preference varchar(255)
    );

    create table profile_custom_exclusions (
        profile_id bigint not null,
        exclusion varchar(255)
    );

    create table profile_custom_intolerances (
        profile_id bigint not null,
        intolerance varchar(255)
    );

    create table profile_custom_proteins (
        profile_id bigint not null,
        protein_source varchar(255)
    );

    create table profile_dietary_restrictions (
        profile_id bigint not null,
        restriction varchar(255)
    );

    create table profile_disliked_foods (
        profile_id bigint not null,
        food varchar(255)
    );

    create table profile_favourite_foods (
        profile_id bigint not null,
        food varchar(255)
    );

    create table profile_food_allergies (
        profile_id bigint not null,
        allergy varchar(255)
    );

    create table profile_food_intolerances (
        profile_id bigint not null,
        intolerance varchar(255)
    );

    create table profile_preferred_cuisines (
        profile_id bigint not null,
        cuisine varchar(255)
    );

    create table profile_preferred_proteins (
        profile_id bigint not null,
        protein_source varchar(255)
    );

    create table reminder (
        enabled boolean not null,
        reminder_time time(6),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        days_of_week varchar(255),
        title varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table sleep_log (
        quality integer,
        created_at timestamp(6) with time zone not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        started_at timestamp(6),
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        notes varchar(1000),
        primary key (id)
    );

    create table user_profile (
        age integer,
        calorie_target integer,
        carb_target integer,
        fat_target integer,
        height_cm float(53),
        hydration_target_ml integer,
        preferred_meals_per_day integer,
        protein_target integer,
        weight_kg float(53),
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        user_id bigint not null unique,
        budget_preference varchar(30),
        meal_prep_difficulty varchar(30),
        meal_prep_time varchar(30),
        dietary_pattern varchar(40),
        custom_dietary_pattern varchar(200),
        dietary_preferences varchar(1000),
        disliked_ingredients varchar(1000),
        activity_level varchar(255),
        fitness_goal varchar(255),
        gender varchar(255),
        primary key (id)
    );

    create table water_log (
        amount_ml integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        logged_at timestamp(6) not null,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        primary key (id)
    );

    create table workout (
        duration_minutes integer,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        started_at timestamp(6),
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        notes varchar(2000),
        name varchar(255) not null,
        primary key (id)
    );

    create table workout_exercise (
        duration_seconds integer,
        exercise_order integer,
        reps integer,
        sets integer,
        weight_kg float(53),
        created_at timestamp(6) with time zone not null,
        exercise_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        workout_id bigint not null,
        notes varchar(1000),
        primary key (id)
    );

    create index idx_goal_user_status 
       on goals (user_id, status);

    create index idx_goal_user_target_date 
       on goals (user_id, target_date);

    alter table if exists body_measurement 
       add constraint FK8ceiblxxlvaxoyiq8vm14o9c0 
       foreign key (user_id) 
       references app_users;

    alter table if exists favourite_exercise 
       add constraint FK1lstsmrxm2395xhf24wj5nvhe 
       foreign key (exercise_id) 
       references exercise;

    alter table if exists favourite_exercise 
       add constraint FKd2spc6887mirwraymj6kcgxys 
       foreign key (user_id) 
       references app_users;

    alter table if exists food 
       add constraint FK53o0bv2ep31n35u4gajjbm9l9 
       foreign key (owner_id) 
       references app_users;

    alter table if exists generated_meal_plan 
       add constraint FK498sn520aayjt54rrqgsjya44 
       foreign key (user_id) 
       references app_users;

    alter table if exists generated_workout_plan 
       add constraint FKayjihprmlsg0tigrb839rbr2u 
       foreign key (user_id) 
       references app_users;

    alter table if exists goals 
       add constraint FKksl5wjm9u3nmvv9cy7e3bu1nw 
       foreign key (user_id) 
       references app_users;

    alter table if exists grocery_lists 
       add constraint FKf497l2am6dany1pjcigxp6m1p 
       foreign key (meal_plan_id) 
       references generated_meal_plan;

    alter table if exists grocery_lists 
       add constraint FKgtkfwimv7qdt0sv73asm67wmp 
       foreign key (user_id) 
       references app_users;

    alter table if exists grocery_item 
       add constraint FKlj59kixv1dpsccv0u9fv26w3m 
       foreign key (grocery_list_id) 
       references grocery_lists;

    alter table if exists meal 
       add constraint FK8ll3fjh9lhxngjr0ft0ivqj6f 
       foreign key (user_id) 
       references app_users;

    alter table if exists meal_food 
       add constraint FKgra778wnc9jcsrtyu2ywbny38 
       foreign key (food_id) 
       references food;

    alter table if exists meal_food 
       add constraint FK9eo5x0xh1wkof5eybyeo8h16i 
       foreign key (meal_id) 
       references meal;

    alter table if exists notification 
       add constraint FKqbdwvce7wteewtihpp7ear8w9 
       foreign key (user_id) 
       references app_users;

    alter table if exists profile_cultural_preferences 
       add constraint FKfcyoqr10ye76ge83bn9cc7a9 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_custom_allergies 
       add constraint FKktm0g9gnhenbbqdx8vgu6rytn 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_custom_cultural_preferences 
       add constraint FKosaqte3ovvctrfma6t23x543x 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_custom_exclusions 
       add constraint FK65n100we2jj2whb51iq4mh5is 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_custom_intolerances 
       add constraint FKbextg3bhc5y82mxsy6epx321d 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_custom_proteins 
       add constraint FK97o8gugv7sxvh282u6k5d32dw 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_dietary_restrictions 
       add constraint FKjjxute3hf62cmdo3u9bs7evua 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_disliked_foods 
       add constraint FKbp7dp7ehsdnngpdklor7kdo3s 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_favourite_foods 
       add constraint FK35ohi92mop0ufvnp8jlaghy3b 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_food_allergies 
       add constraint FKoli9hgxji79ct5wns5yllb1s8 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_food_intolerances 
       add constraint FKd6iqgobxe7mu33kb9d67uh8j0 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_preferred_cuisines 
       add constraint FKqxe2l1w1f39ues11wdmay9kgo 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists profile_preferred_proteins 
       add constraint FK7ufeq29xtvs0vgamnrr38493j 
       foreign key (profile_id) 
       references user_profile;

    alter table if exists reminder 
       add constraint FKqsdemjg334x7x6hsovf3cacy7 
       foreign key (user_id) 
       references app_users;

    alter table if exists sleep_log 
       add constraint FKioe5gtawmxbrt6ixjqmx5xjqq 
       foreign key (user_id) 
       references app_users;

    alter table if exists user_profile 
       add constraint FKo147a12pvkvo2092u5yp6ufv 
       foreign key (user_id) 
       references app_users;

    alter table if exists water_log 
       add constraint FK4ejq0p0iynojchgcwkyjk3sre 
       foreign key (user_id) 
       references app_users;

    alter table if exists workout 
       add constraint FK9dfm98unw7r4v9lo0a9m86l22 
       foreign key (user_id) 
       references app_users;

    alter table if exists workout_exercise 
       add constraint FKalytxvdcpsg2e2oo8ihk55dm2 
       foreign key (exercise_id) 
       references exercise;

    alter table if exists workout_exercise
       add constraint FKqultuq4g6w47iqdaf0vb8ff3j
       foreign key (workout_id)
       references workout;

-- ============================================================
-- Supabase security lockdown (IMPORTANT)
-- The Spring Boot backend connects with the direct Postgres role
-- (via the connection string), which BYPASSES RLS — so the app keeps
-- full access. This block only locks the auto-exposed PostgREST API
-- (anon / authenticated keys) so these tables are NOT publicly readable.
-- Enable RLS on every table and add NO policies = deny all via the API.
-- ============================================================
do $$
declare t text;
begin
  for t in
    select tablename from pg_tables where schemaname = 'public'
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('revoke all on public.%I from anon, authenticated;', t);
  end loop;
end $$;
