import { useEffect, useMemo, useState } from "react";
import { CircleGauge, Pencil, Plus, Scale, Trash2 } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, FormField, inputClass, Modal, PageHeader, PillButton } from "../components/ui";
import { api } from "../services/api";
import type { BodyMeasurement, BodySummary } from "../types";

const localDate = () => { const now = new Date(); const offset = now.getTimezoneOffset() * 60000; return new Date(now.getTime() - offset).toISOString().slice(0,10); };
const empty = (): Omit<BodyMeasurement,"id"> => ({ measuredOn: localDate(), notes: "" });
const formatChange = (value?: number, unit = "") => value == null ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(1)}${unit}`;

export default function BodyPage() {
  const [summary,setSummary] = useState<BodySummary|null>(null); const [editing,setEditing] = useState<BodyMeasurement|null|"new">(null); const [form,setForm] = useState(empty()); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const load = () => api.getMeasurementSummary().then(setSummary).catch(e => setError(e.message)); useEffect(()=>{void load();},[]);
  const chart = useMemo(() => [...(summary?.history ?? [])].reverse().filter(e=>e.weightKg!=null).map(e=>({date:new Date(`${e.measuredOn}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"}),weight:e.weightKg,bodyFat:e.bodyFatPercentage,waist:e.waistCm})),[summary]);
  const open = (entry?:BodyMeasurement) => {setError("");setEditing(entry??"new");setForm(entry?{...entry}:empty());};
  const number = (key:keyof Omit<BodyMeasurement,"id">, value:string) => setForm({...form,[key]:value===""?undefined:Number(value)});
  const save = async()=>{setSaving(true);setError("");try{const values=[form.weightKg,form.bodyFatPercentage,form.chestCm,form.waistCm,form.hipsCm,form.armsCm,form.thighsCm].filter((value):value is number=>value!=null);if(!form.measuredOn)throw new Error("Choose a measurement date.");if(!values.length)throw new Error("Enter at least one body measurement.");if(form.measuredOn>localDate())throw new Error("Measurement date cannot be in the future.");if(form.weightKg!=null&&(form.weightKg<20||form.weightKg>500))throw new Error("Weight must be between 20 and 500 kg.");if(form.bodyFatPercentage!=null&&(form.bodyFatPercentage<1||form.bodyFatPercentage>70))throw new Error("Body fat must be between 1% and 70%.");if(values.some(value=>value<=0))throw new Error("Measurements must be positive values.");if(editing!=="new"&&editing)await api.updateMeasurement(editing.id,form);else await api.createMeasurement(form);setEditing(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save measurement");}finally{setSaving(false);}};
  const remove=async(entry:BodyMeasurement)=>{if(!window.confirm(`Delete measurements from ${entry.measuredOn}?`))return;setError("");try{await api.deleteMeasurement(entry.id);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to delete measurement");}};
  const metrics = [{label:"Weight",value:summary?.latestWeight,change:summary?.weightChange,unit:" kg"},{label:"Body fat",value:summary?.latestBodyFat,change:summary?.bodyFatChange,unit:"%"},{label:"Waist",value:summary?.latestWaist,change:summary?.waistChange,unit:" cm"}];
  return <div><PageHeader eyebrow="Measurements" title="Body" description="Track meaningful change beyond the scale." action={<PillButton onClick={()=>open()} className="bg-ink text-white"><Plus size={16}/>Add measurement</PillButton>}/>
    {error&&!editing&&<p className="mb-4 rounded-2xl bg-[#fff1ef] p-4 text-sm font-semibold text-coral">{error}</p>}
    {!summary&&!error?<div className="h-80 animate-pulse rounded-card bg-white"/>:summary?<><div className="grid gap-4 md:grid-cols-3">{metrics.map(({label,value,change,unit},i)=><Card key={label} className="p-6"><span className={`grid size-11 place-items-center rounded-2xl ${i===0?"bg-[#eeeaff] text-violet":"bg-[#f4f4f1]"}`}>{i===0?<Scale size={19}/>:<CircleGauge size={19}/>}</span><p className="mt-7 text-sm font-semibold text-muted">{label}</p><p className="mt-1 text-[32px] font-bold tracking-[-.04em]">{value==null?"—":`${value.toFixed(1)}${unit}`}</p><p className="mt-2 text-xs font-bold text-violet">{formatChange(change,unit)} across history</p></Card>)}</div>
      <Card className="mt-4 p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Weight trend</h2><p className="mt-1 text-sm text-muted">Persisted measurement history</p></div></div>{chart.length?<div className="mt-6 h-64"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="bodyFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7357ff" stopOpacity={.22}/><stop offset="1" stopColor="#7357ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="date" axisLine={false} tickLine={false}/><YAxis hide domain={["dataMin - 1","dataMax + 1"]}/><Tooltip contentStyle={{background:"var(--chart-tooltip)",border:"1px solid var(--chart-tooltip-border)",borderRadius:14}}/><Area dataKey="weight" stroke="#7357ff" strokeWidth={3} fill="url(#bodyFill)"/></AreaChart></ResponsiveContainer></div>:<div className="mt-6 rounded-[22px] bg-[#f7f7f4] px-6 py-12 text-center"><Scale className="mx-auto text-muted"/><h3 className="mt-4 font-bold">No body measurements yet</h3><p className="mt-2 text-sm text-muted">Add your first entry to begin seeing progress trends.</p><PillButton onClick={()=>open()} className="mt-5 bg-ink text-white">Add measurement</PillButton></div>}</Card>
      {!!summary.history.length&&<Card className="mt-4 p-7"><h2 className="text-xl font-bold">Measurement history</h2><div className="mt-5 divide-y divide-black/[.055]">{summary.history.map(entry=><div key={entry.id} className="flex flex-wrap items-center gap-4 py-4"><div className="min-w-[160px] flex-1"><p className="font-bold">{new Date(`${entry.measuredOn}T00:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"long",year:"numeric"})}</p><p className="text-xs text-muted">{[entry.weightKg&&`${entry.weightKg} kg`,entry.bodyFatPercentage&&`${entry.bodyFatPercentage}% fat`,entry.waistCm&&`${entry.waistCm} cm waist`].filter(Boolean).join(" · ")}</p></div><button onClick={()=>open(entry)} className="grid size-9 place-items-center rounded-full hover:bg-black/5" aria-label="Edit measurement"><Pencil size={15}/></button><button onClick={()=>remove(entry)} className="grid size-9 place-items-center rounded-full text-muted hover:bg-[#fff1ef] hover:text-coral" aria-label="Delete measurement"><Trash2 size={15}/></button></div>)}</div></Card>}</>:null}
    {editing&&<Modal title={editing==="new"?"Add measurement":"Edit measurement"} onClose={()=>setEditing(null)}><div className="space-y-4"><FormField label="Date"><input type="date" max={localDate()} className={inputClass} value={form.measuredOn} onChange={e=>setForm({...form,measuredOn:e.target.value})}/></FormField><div className="grid gap-3 sm:grid-cols-2">{[["Weight (kg)","weightKg",20,500],["Body fat (%)","bodyFatPercentage",1,70],["Chest (cm)","chestCm",10,400],["Waist (cm)","waistCm",10,400],["Hips (cm)","hipsCm",10,400],["Arms (cm)","armsCm",10,400],["Thighs (cm)","thighsCm",10,400]].map(([label,key,min,max])=><FormField key={String(key)} label={String(label)}><input type="number" step="0.1" min={Number(min)} max={Number(max)} className={inputClass} value={(form[key as keyof typeof form] as number|undefined)??""} onChange={e=>number(key as keyof Omit<BodyMeasurement,"id">,e.target.value)}/></FormField>)}</div><FormField label="Notes (optional)"><textarea className={`${inputClass} h-20 py-3`} value={form.notes??""} onChange={e=>setForm({...form,notes:e.target.value})}/></FormField>{error&&<p className="text-sm font-semibold text-coral">{error}</p>}<PillButton disabled={saving} onClick={save} className="w-full bg-ink text-white">{saving?"Saving…":"Save measurements"}</PillButton></div></Modal>}
  </div>;
}
