import { useEffect, useState } from "react";
import { Activity, ArrowRight, Download, Droplets, Dumbbell, Flame, MoonStar, Scale, Target, TrendingDown, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, MetricItem, MetricStrip, PageHeader, PillButton, SectionHeader, SegmentedControl } from "../components/ui";
import { api } from "../services/api";
import type { ProgressSummary } from "../types";
import type { ComparisonSummary, Goal, RecoverySummary } from "../types";
import { HealthCalendar } from "../components/HealthCalendar";
import { Link } from "react-router-dom";

const minutes = (value: number) => `${Math.floor(value / 60)}h ${Math.round(value % 60)}m`;
const tabs = ["Overview", "Goals", "Training", "Nutrition", "Recovery", "Body"];

export default function ProgressPage() {
  const [range, setRange] = useState<"week" | "month">("week");
  const [tab, setTab] = useState("Overview");
  const [data, setData] = useState<ProgressSummary | null>(null);
  const [comparison, setComparison] = useState<ComparisonSummary | null>(null);
  const [recovery, setRecovery] = useState<RecoverySummary | null>(null);
  const [goals, setGoals] = useState<Goal[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { setData(null); setError(""); api.getProgress(range).then(setData).catch(reason => setError(reason instanceof Error ? reason.message : "Unable to load progress")); }, [range]);
  useEffect(() => { Promise.all([api.getProgressComparison(),api.getRecovery(),api.getGoals()]).then(([comparisonData,recoveryData,goalData])=>{setComparison(comparisonData);setRecovery(recoveryData);setGoals(goalData);}).catch(()=>undefined); }, []);
  const exportCsv = () => {
    if (!data) return;
    const rows = ["date,workouts,duration_minutes,volume_kg,calories,protein_g,water_ml,sleep_hours,weight_kg", ...data.timeline.map(point => [point.date, point.workouts, point.durationMinutes, point.volumeKg, point.calories, point.protein, point.waterMl, point.sleepHours, point.weight ?? ""].join(","))];
    const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `circle-health-progress-${range}.csv`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0);
  };
  const chart = tab === "Training" ? { title: "Training volume", detail: "Load moved across completed workouts", key: "volumeKg", color: "#7357ff", bar: true }
    : tab === "Nutrition" ? { title: "Daily energy", detail: "Calories recorded each day", key: "calories", color: "#ff6b57", bar: false }
      : tab === "Recovery" ? { title: "Sleep duration", detail: "Hours of sleep each night", key: "sleepHours", color: "#765bd6", bar: false }
        : tab === "Body" ? { title: "Weight trend", detail: "Persisted body measurements", key: "weight", color: "var(--text-primary)", bar: false }
          : { title: "Daily consistency", detail: "Workout duration across the selected range", key: "durationMinutes", color: "#2ba75c", bar: true };
  return <div>
    <PageHeader eyebrow="Trends" title="Progress" description="See the signal across training, nutrition and recovery." action={<div className="flex gap-2"><SegmentedControl options={["Week", "Month"]} value={range === "week" ? "Week" : "Month"} onChange={value => setRange(value.toLowerCase() as "week" | "month")}/><PillButton onClick={exportCsv} disabled={!data} className="min-h-10 bg-white px-4 text-ink shadow-sm"><Download size={15}/>Export</PillButton></div>}/>
    {error && <p className="mb-4 rounded-2xl bg-[#fff1ef] p-4 text-sm font-semibold text-coral">{error}</p>}
    {!data && !error ? <div className="h-72 animate-pulse rounded-card bg-white"/> : data ? <>
      <MetricStrip className="grid-cols-2 sm:grid-cols-3 xl:grid-cols-5">
        <MetricItem label="Workouts" value={data.workouts.count} detail={`${data.workouts.workoutsPerWeek.toFixed(1)} per week`} icon={<Dumbbell size={16}/>} accent="bg-violet"/>
        <MetricItem label="Training time" value={minutes(data.workouts.totalDurationMinutes)} detail={`${Math.round(data.workouts.trainingVolumeKg).toLocaleString()} kg volume`} icon={<Activity size={16}/>} accent="bg-[#2ba75c]"/>
        <MetricItem label="Avg calories" value={Math.round(data.nutrition.averageCalories).toLocaleString()} detail={`${data.nutrition.calorieTargetDays} target days`} icon={<Flame size={16}/>} accent="bg-coral"/>
        <MetricItem label="Hydration" value={`${Math.round(data.hydration.goalPercentage)}%`} detail={`${Math.round(data.hydration.averageDailyMl).toLocaleString()} ml average`} icon={<Droplets size={16}/>} accent="bg-cyan"/>
        <MetricItem label="Sleep" value={minutes(data.sleep.averageMinutes)} detail={`${data.sleep.averageQuality.toFixed(1)}/5 quality`} icon={<MoonStar size={16}/>} accent="bg-[#765bd6]"/>
      </MetricStrip>
      <HealthCalendar/>
      {tab === "Goals" ? <Card className="mt-4 p-5 md:p-6"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-muted">Trackable outcomes</p><h2 className="mt-1 text-xl font-bold">Goals & timelines</h2></div><Link to="/goals" className="text-xs font-bold">Manage goals <ArrowRight size={13} className="inline"/></Link></div><div className="mt-4 divide-y divide-line">{goals.filter(goal=>goal.status==="ACTIVE").slice(0,4).map(goal=><Link key={goal.id} to="/goals" className="grid gap-3 py-4 sm:grid-cols-[1fr_180px_110px] sm:items-center"><div><p className="text-sm font-bold">{goal.title}</p><p className="mt-1 text-xs text-muted">{goal.currentValue == null ? "Awaiting data" : `${goal.currentValue.toFixed(goal.currentValue%1?1:0)} ${goal.unit}`} → {goal.targetValue} {goal.unit}</p></div><div><div className="h-1.5 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-coral" style={{width:`${goal.progress}%`}}/></div><p className="mt-1 text-[10px] text-muted">{Math.round(goal.progress)}% complete</p></div><span className="text-xs font-bold capitalize">{goal.trackStatus.toLowerCase().replaceAll("_"," ")}</span></Link>)}{!goals.some(goal=>goal.status==="ACTIVE")&&<div className="py-8 text-center"><Target className="mx-auto text-muted"/><p className="mt-2 text-sm text-muted">No active goals.</p><Link to="/goals?new=1" className="mt-2 inline-block text-xs font-bold text-coral">Create your first goal</Link></div>}</div></Card> : <Card className="mt-4 p-5 md:p-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><SectionHeader title={chart.title} description={chart.detail}/><div className="flex max-w-full gap-1 overflow-x-auto rounded-full bg-[#f1f1ee] p-1" role="tablist">{tabs.map(item => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-semibold ${tab === item ? "bg-white shadow-sm" : "text-muted"}`}>{item}</button>)}</div></div>
        <div className="mt-5 h-[240px]">{data.timeline.some(point => point[chart.key as keyof typeof point] != null) ? <ResponsiveContainer>{chart.bar ? <BarChart data={data.timeline}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="date" tickFormatter={value => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short" })} axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "var(--chart-label)" }}/><YAxis hide/><Tooltip contentStyle={{ border: "1px solid var(--chart-tooltip-border)", background:"var(--chart-tooltip)", borderRadius: 12 }}/><Bar dataKey={chart.key} fill={chart.color} radius={[6, 6, 2, 2]}/></BarChart> : <LineChart data={data.timeline}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="date" tickFormatter={value => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short" })} axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "var(--chart-label)" }}/><YAxis hide domain={["auto", "auto"]}/><Tooltip contentStyle={{ border: "1px solid var(--chart-tooltip-border)", background:"var(--chart-tooltip)", borderRadius: 12 }}/><Line type="monotone" dataKey={chart.key} stroke={chart.color} strokeWidth={3} connectNulls dot={{ r: 3, fill: chart.color, stroke: "var(--surface)", strokeWidth: 2 }}/></LineChart>}</ResponsiveContainer> : <div className="grid h-full place-items-center rounded-2xl bg-surface-muted text-sm text-muted">No {tab.toLowerCase()} data in this range.</div>}</div>
        <div className="mt-4 grid gap-3 border-t border-black/[0.055] pt-4 sm:grid-cols-3"><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-muted">Current streak</p><p className="mt-1 text-lg font-bold"><Flame size={15} className="mr-1 inline text-coral"/>{data.streak.current} days</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-muted">Latest weight</p><p className="mt-1 text-lg font-bold"><Scale size={15} className="mr-1 inline"/>{data.body.latestWeight ? `${data.body.latestWeight.toFixed(1)} kg` : "No data"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.1em] text-muted">Average protein</p><p className="mt-1 text-lg font-bold">{Math.round(data.nutrition.averageProtein)} g</p></div></div>
      </Card>}
      {(tab === "Overview" || tab === "Recovery") && <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_.55fr]">{comparison&&<Card className="p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-muted">Compare</p><h2 className="mt-1 text-lg font-bold">{comparison.label}</h2></div><div className="mt-4 grid gap-px overflow-hidden rounded-2xl bg-line sm:grid-cols-2 lg:grid-cols-3">{comparison.metrics.map(metric=><div key={metric.key} className="bg-surface p-3.5"><p className="text-[10px] font-bold uppercase text-muted">{metric.label}</p><div className="mt-2 flex items-end justify-between"><p className="text-lg font-bold">{Math.round(metric.current).toLocaleString()} <span className="text-[9px] text-muted">{metric.unit}</span></p>{metric.percentChange!=null&&<span className={`flex items-center text-[10px] font-bold ${metric.percentChange>=0?"text-success":"text-coral"}`}>{metric.percentChange>=0?<TrendingUp size={12}/>:<TrendingDown size={12}/>} {Math.abs(metric.percentChange)}%</span>}</div><p className="mt-1 text-[10px] text-muted">{metric.previous==null?"Not enough previous data":`${Math.round(metric.previous).toLocaleString()} ${metric.unit} last week`}</p></div>)}</div></Card>}{recovery&&<Card className="border-0 bg-ink p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-white/45">Recovery</p><div className="mt-2 flex items-end gap-2"><p className="text-4xl font-bold tracking-[-.05em]">{recovery.score}</p><p className="pb-1 text-xs font-bold text-white/55">{recovery.rating.toUpperCase()}</p></div><div className="mt-4 space-y-2">{[["Sleep",recovery.sleepScore],["Hydration",recovery.hydrationScore],["Training load",recovery.trainingLoadScore]].map(([label,value])=><div key={String(label)} className="flex items-center gap-2 text-xs"><span className="w-24 text-white/55">{label}</span><div className="h-1 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-violet" style={{width:`${value}%`}}/></div><span className="w-6 text-right font-bold">{value}</span></div>)}</div><p className="mt-4 text-[10px] leading-4 text-white/40">{recovery.disclaimer}</p></Card>}</div>}
    </> : null}
  </div>;
}
