--
-- Circle Health PostgreSQL schema
-- Generated from the verified local application database on 2026-08-20.
-- This file contains structure only; it does not contain user records or secrets.
--


-- Dumped from database version 14.20 (Homebrew)
-- Dumped by pg_dump version 14.20 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    email character varying(180) NOT NULL,
    name character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: body_measurement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.body_measurement (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    arms_cm double precision,
    body_fat_percentage double precision,
    chest_cm double precision,
    hips_cm double precision,
    measured_on date NOT NULL,
    thighs_cm double precision,
    waist_cm double precision,
    weight_kg double precision,
    user_id bigint NOT NULL,
    notes character varying(1000)
);


--
-- Name: body_measurement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.body_measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.body_measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercise (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    difficulty character varying(255),
    equipment character varying(255),
    instructions character varying(3000),
    media_url character varying(255),
    muscle_group character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favourite_exercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favourite_exercise (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    exercise_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favourite_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favourite_exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favourite_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.food (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    barcode character varying(255),
    brand character varying(255),
    calories double precision,
    carbohydrates double precision,
    custom_food boolean NOT NULL,
    fat double precision,
    fibre double precision,
    name character varying(255) NOT NULL,
    protein double precision,
    serving_size double precision,
    serving_unit character varying(255),
    owner_id bigint,
    saturated_fat double precision,
    sugar double precision,
    allergen_tags character varying(2000),
    dietary_tags character varying(2000),
    ingredients_text character varying(5000),
    measurement_type character varying(255),
    nutrition_basis_quantity double precision,
    nutrition_basis_unit character varying(255),
    package_quantity double precision,
    package_unit character varying(255),
    suggested_serving_quantity double precision,
    suggested_serving_unit character varying(255)
);


--
-- Name: food_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generated_meal_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generated_meal_plan (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    calorie_target integer,
    grocery_list_json text,
    name character varying(255) NOT NULL,
    plan_json text,
    saved boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: generated_meal_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generated_meal_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generated_meal_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generated_workout_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generated_workout_plan (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    days_per_week integer,
    goal character varying(255),
    name character varying(255) NOT NULL,
    plan_json text,
    saved boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: generated_workout_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generated_workout_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generated_workout_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    completed_date date,
    direction character varying(20) NOT NULL,
    start_date date NOT NULL,
    start_value double precision,
    status character varying(20) NOT NULL,
    target_date date,
    target_value double precision NOT NULL,
    title character varying(140) NOT NULL,
    type character varying(40) NOT NULL,
    unit character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT goals_direction_check CHECK (((direction)::text = ANY ((ARRAY['DECREASE'::character varying, 'INCREASE'::character varying, 'MAINTAIN'::character varying, 'AT_LEAST'::character varying, 'AT_MOST'::character varying])::text[]))),
    CONSTRAINT goals_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'PAUSED'::character varying, 'FAILED'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT goals_type_check CHECK (((type)::text = ANY ((ARRAY['WEIGHT'::character varying, 'BODY_FAT'::character varying, 'WAIST'::character varying, 'PROTEIN'::character varying, 'CALORIES'::character varying, 'WATER'::character varying, 'SLEEP'::character varying, 'WORKOUT_FREQUENCY'::character varying, 'STREAK'::character varying])::text[])))
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grocery_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grocery_item (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    category character varying(255),
    checked boolean NOT NULL,
    name character varying(255) NOT NULL,
    quantity double precision,
    unit character varying(255),
    grocery_list_id bigint NOT NULL,
    item_order integer
);


--
-- Name: grocery_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grocery_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grocery_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grocery_lists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grocery_lists (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    name character varying(255) NOT NULL,
    meal_plan_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: grocery_lists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grocery_lists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grocery_lists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meal (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    eaten_at timestamp(6) without time zone,
    meal_type character varying(255),
    name character varying(255) NOT NULL,
    quality_score integer,
    reusable boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: meal_food; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meal_food (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    quantity double precision,
    unit character varying(255),
    food_id bigint NOT NULL,
    meal_id bigint NOT NULL
);


--
-- Name: meal_food_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meal_food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meal_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    message character varying(1000) NOT NULL,
    read_at timestamp(6) with time zone,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile_cultural_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_cultural_preferences (
    profile_id bigint NOT NULL,
    preference character varying(255)
);


--
-- Name: profile_custom_allergies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_custom_allergies (
    profile_id bigint NOT NULL,
    allergy character varying(255)
);


--
-- Name: profile_custom_cultural_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_custom_cultural_preferences (
    profile_id bigint NOT NULL,
    preference character varying(255)
);


--
-- Name: profile_custom_exclusions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_custom_exclusions (
    profile_id bigint NOT NULL,
    exclusion character varying(255)
);


--
-- Name: profile_custom_intolerances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_custom_intolerances (
    profile_id bigint NOT NULL,
    intolerance character varying(255)
);


--
-- Name: profile_custom_proteins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_custom_proteins (
    profile_id bigint NOT NULL,
    protein_source character varying(255)
);


--
-- Name: profile_dietary_restrictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_dietary_restrictions (
    profile_id bigint NOT NULL,
    restriction character varying(255)
);


--
-- Name: profile_disliked_foods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_disliked_foods (
    profile_id bigint NOT NULL,
    food character varying(255)
);


--
-- Name: profile_favourite_foods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_favourite_foods (
    profile_id bigint NOT NULL,
    food character varying(255)
);


--
-- Name: profile_food_allergies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_food_allergies (
    profile_id bigint NOT NULL,
    allergy character varying(255)
);


--
-- Name: profile_food_intolerances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_food_intolerances (
    profile_id bigint NOT NULL,
    intolerance character varying(255)
);


--
-- Name: profile_preferred_cuisines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_preferred_cuisines (
    profile_id bigint NOT NULL,
    cuisine character varying(255)
);


--
-- Name: profile_preferred_proteins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_preferred_proteins (
    profile_id bigint NOT NULL,
    protein_source character varying(255)
);


--
-- Name: reminder; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reminder (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    days_of_week character varying(255),
    enabled boolean NOT NULL,
    reminder_time time(6) without time zone,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: reminder_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reminder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reminder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sleep_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sleep_log (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    ended_at timestamp(6) without time zone,
    notes character varying(1000),
    quality integer,
    started_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: sleep_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sleep_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sleep_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    activity_level character varying(255),
    age integer,
    calorie_target integer,
    carb_target integer,
    dietary_preferences character varying(1000),
    disliked_ingredients character varying(1000),
    fat_target integer,
    fitness_goal character varying(255),
    gender character varying(255),
    height_cm double precision,
    hydration_target_ml integer,
    protein_target integer,
    weight_kg double precision,
    user_id bigint NOT NULL,
    budget_preference character varying(30),
    custom_dietary_pattern character varying(200),
    dietary_pattern character varying(40),
    meal_prep_difficulty character varying(30),
    meal_prep_time character varying(30),
    preferred_meals_per_day integer
);


--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: water_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.water_log (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    amount_ml integer NOT NULL,
    logged_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: water_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.water_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.water_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workout (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    duration_minutes integer,
    name character varying(255) NOT NULL,
    notes character varying(2000),
    started_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: workout_exercise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workout_exercise (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    duration_seconds integer,
    notes character varying(1000),
    reps integer,
    sets integer,
    weight_kg double precision,
    exercise_id bigint NOT NULL,
    workout_id bigint NOT NULL,
    exercise_order integer
);


--
-- Name: workout_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workout_exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: body_measurement body_measurement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.body_measurement
    ADD CONSTRAINT body_measurement_pkey PRIMARY KEY (id);


--
-- Name: exercise exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT exercise_pkey PRIMARY KEY (id);


--
-- Name: favourite_exercise favourite_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favourite_exercise
    ADD CONSTRAINT favourite_exercise_pkey PRIMARY KEY (id);


--
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (id);


--
-- Name: generated_meal_plan generated_meal_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_meal_plan
    ADD CONSTRAINT generated_meal_plan_pkey PRIMARY KEY (id);


--
-- Name: generated_workout_plan generated_workout_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_workout_plan
    ADD CONSTRAINT generated_workout_plan_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: grocery_item grocery_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grocery_item
    ADD CONSTRAINT grocery_item_pkey PRIMARY KEY (id);


--
-- Name: grocery_lists grocery_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT grocery_lists_pkey PRIMARY KEY (id);


--
-- Name: meal_food meal_food_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal_food
    ADD CONSTRAINT meal_food_pkey PRIMARY KEY (id);


--
-- Name: meal meal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal
    ADD CONSTRAINT meal_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: reminder reminder_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reminder
    ADD CONSTRAINT reminder_pkey PRIMARY KEY (id);


--
-- Name: sleep_log sleep_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sleep_log
    ADD CONSTRAINT sleep_log_pkey PRIMARY KEY (id);


--
-- Name: food uk1ror028moynn6re628ydpy848; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT uk1ror028moynn6re628ydpy848 UNIQUE (barcode);


--
-- Name: app_users uk4vj92ux8a2eehds1mdvmks473; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);


--
-- Name: user_profile ukebc21hy5j7scdvcjt0jy6xxrv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT ukebc21hy5j7scdvcjt0jy6xxrv UNIQUE (user_id);


--
-- Name: favourite_exercise ukeyxyerghrvfvngyasp3d6vhg9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favourite_exercise
    ADD CONSTRAINT ukeyxyerghrvfvngyasp3d6vhg9 UNIQUE (user_id, exercise_id);


--
-- Name: exercise ukr1ox34byx8pj01qd39plfobsj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT ukr1ox34byx8pj01qd39plfobsj UNIQUE (name);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: water_log water_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.water_log
    ADD CONSTRAINT water_log_pkey PRIMARY KEY (id);


--
-- Name: workout_exercise workout_exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workout_exercise
    ADD CONSTRAINT workout_exercise_pkey PRIMARY KEY (id);


--
-- Name: workout workout_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workout
    ADD CONSTRAINT workout_pkey PRIMARY KEY (id);


--
-- Name: idx_goal_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_user_status ON public.goals USING btree (user_id, status);


--
-- Name: idx_goal_user_target_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_user_target_date ON public.goals USING btree (user_id, target_date);


--
-- Name: favourite_exercise fk1lstsmrxm2395xhf24wj5nvhe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favourite_exercise
    ADD CONSTRAINT fk1lstsmrxm2395xhf24wj5nvhe FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: profile_favourite_foods fk35ohi92mop0ufvnp8jlaghy3b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_favourite_foods
    ADD CONSTRAINT fk35ohi92mop0ufvnp8jlaghy3b FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: generated_meal_plan fk498sn520aayjt54rrqgsjya44; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_meal_plan
    ADD CONSTRAINT fk498sn520aayjt54rrqgsjya44 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: water_log fk4ejq0p0iynojchgcwkyjk3sre; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.water_log
    ADD CONSTRAINT fk4ejq0p0iynojchgcwkyjk3sre FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: food fk53o0bv2ep31n35u4gajjbm9l9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT fk53o0bv2ep31n35u4gajjbm9l9 FOREIGN KEY (owner_id) REFERENCES public.app_users(id);


--
-- Name: profile_custom_exclusions fk65n100we2jj2whb51iq4mh5is; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_custom_exclusions
    ADD CONSTRAINT fk65n100we2jj2whb51iq4mh5is FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: profile_preferred_proteins fk7ufeq29xtvs0vgamnrr38493j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_preferred_proteins
    ADD CONSTRAINT fk7ufeq29xtvs0vgamnrr38493j FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: body_measurement fk8ceiblxxlvaxoyiq8vm14o9c0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.body_measurement
    ADD CONSTRAINT fk8ceiblxxlvaxoyiq8vm14o9c0 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: meal fk8ll3fjh9lhxngjr0ft0ivqj6f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal
    ADD CONSTRAINT fk8ll3fjh9lhxngjr0ft0ivqj6f FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_custom_proteins fk97o8gugv7sxvh282u6k5d32dw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_custom_proteins
    ADD CONSTRAINT fk97o8gugv7sxvh282u6k5d32dw FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: workout fk9dfm98unw7r4v9lo0a9m86l22; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workout
    ADD CONSTRAINT fk9dfm98unw7r4v9lo0a9m86l22 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: meal_food fk9eo5x0xh1wkof5eybyeo8h16i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal_food
    ADD CONSTRAINT fk9eo5x0xh1wkof5eybyeo8h16i FOREIGN KEY (meal_id) REFERENCES public.meal(id);


--
-- Name: workout_exercise fkalytxvdcpsg2e2oo8ihk55dm2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workout_exercise
    ADD CONSTRAINT fkalytxvdcpsg2e2oo8ihk55dm2 FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: generated_workout_plan fkayjihprmlsg0tigrb839rbr2u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_workout_plan
    ADD CONSTRAINT fkayjihprmlsg0tigrb839rbr2u FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_custom_intolerances fkbextg3bhc5y82mxsy6epx321d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_custom_intolerances
    ADD CONSTRAINT fkbextg3bhc5y82mxsy6epx321d FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: profile_disliked_foods fkbp7dp7ehsdnngpdklor7kdo3s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_disliked_foods
    ADD CONSTRAINT fkbp7dp7ehsdnngpdklor7kdo3s FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: favourite_exercise fkd2spc6887mirwraymj6kcgxys; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favourite_exercise
    ADD CONSTRAINT fkd2spc6887mirwraymj6kcgxys FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_food_intolerances fkd6iqgobxe7mu33kb9d67uh8j0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_food_intolerances
    ADD CONSTRAINT fkd6iqgobxe7mu33kb9d67uh8j0 FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: grocery_lists fkf497l2am6dany1pjcigxp6m1p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT fkf497l2am6dany1pjcigxp6m1p FOREIGN KEY (meal_plan_id) REFERENCES public.generated_meal_plan(id);


--
-- Name: profile_cultural_preferences fkfcyoqr10ye76ge83bn9cc7a9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_cultural_preferences
    ADD CONSTRAINT fkfcyoqr10ye76ge83bn9cc7a9 FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: meal_food fkgra778wnc9jcsrtyu2ywbny38; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meal_food
    ADD CONSTRAINT fkgra778wnc9jcsrtyu2ywbny38 FOREIGN KEY (food_id) REFERENCES public.food(id);


--
-- Name: grocery_lists fkgtkfwimv7qdt0sv73asm67wmp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grocery_lists
    ADD CONSTRAINT fkgtkfwimv7qdt0sv73asm67wmp FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: sleep_log fkioe5gtawmxbrt6ixjqmx5xjqq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sleep_log
    ADD CONSTRAINT fkioe5gtawmxbrt6ixjqmx5xjqq FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_dietary_restrictions fkjjxute3hf62cmdo3u9bs7evua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_dietary_restrictions
    ADD CONSTRAINT fkjjxute3hf62cmdo3u9bs7evua FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: goals fkksl5wjm9u3nmvv9cy7e3bu1nw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fkksl5wjm9u3nmvv9cy7e3bu1nw FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_custom_allergies fkktm0g9gnhenbbqdx8vgu6rytn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_custom_allergies
    ADD CONSTRAINT fkktm0g9gnhenbbqdx8vgu6rytn FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: grocery_item fklj59kixv1dpsccv0u9fv26w3m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grocery_item
    ADD CONSTRAINT fklj59kixv1dpsccv0u9fv26w3m FOREIGN KEY (grocery_list_id) REFERENCES public.grocery_lists(id);


--
-- Name: user_profile fko147a12pvkvo2092u5yp6ufv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT fko147a12pvkvo2092u5yp6ufv FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: profile_food_allergies fkoli9hgxji79ct5wns5yllb1s8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_food_allergies
    ADD CONSTRAINT fkoli9hgxji79ct5wns5yllb1s8 FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: profile_custom_cultural_preferences fkosaqte3ovvctrfma6t23x543x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_custom_cultural_preferences
    ADD CONSTRAINT fkosaqte3ovvctrfma6t23x543x FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- Name: notification fkqbdwvce7wteewtihpp7ear8w9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkqbdwvce7wteewtihpp7ear8w9 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: reminder fkqsdemjg334x7x6hsovf3cacy7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reminder
    ADD CONSTRAINT fkqsdemjg334x7x6hsovf3cacy7 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: workout_exercise fkqultuq4g6w47iqdaf0vb8ff3j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workout_exercise
    ADD CONSTRAINT fkqultuq4g6w47iqdaf0vb8ff3j FOREIGN KEY (workout_id) REFERENCES public.workout(id);


--
-- Name: profile_preferred_cuisines fkqxe2l1w1f39ues11wdmay9kgo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_preferred_cuisines
    ADD CONSTRAINT fkqxe2l1w1f39ues11wdmay9kgo FOREIGN KEY (profile_id) REFERENCES public.user_profile(id);


--
-- PostgreSQL database dump complete
--
